# ----------------------- #
#      Main Configs       #
# ----------------------- #

url:
title: "#umani2018"
email: umangwedsdhwani@gmail.com
author: Umang Mehta
description: > # "Write an awesome description for your new site here.
copyright: 'Copyright &copy; #umani2018. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/umani2018
  - title: facebook
    url: https://www.facebook.com/umaani
  - title: youtube
    url: https://youtu.be/T47abjpsbsY
  - title: google-plus
    url: https://drive.google.com/open?id=1KaXg4WzYrs0SluOu5d0KPJiDqx-DM7br
